from pathlib import Path
import sys

if len(sys.argv) != 3:
    raise SystemExit("usage: patch_cross_asset_wfv_v2.py INPUT OUTPUT")
source = Path(sys.argv[1])
target = Path(sys.argv[2])
s = source.read_text(encoding="utf-8")
repls = []
repls.append(('''    kline = kline.loc[(kline.index >= start) & (kline.index < end)].copy()\n\n    metrics = pd.read_parquet(source["metrics"]["local_path"])\n''','''    kline = kline.loc[(kline.index >= start) & (kline.index < end)].copy()\n    if len(kline) and ((kline.index.view("i8") % pd.Timedelta(minutes=5).value) != 0).any():\n        raise RuntimeError("kline timestamps are not aligned to exact 5-minute boundaries")\n    expected_index = pd.date_range(start.ceil("5min"), end, freq="5min", inclusive="left", tz="UTC")\n    kline = kline.reindex(expected_index)\n    kline.index.name = "time"\n    kline["bar_present"] = kline[["open", "high", "low", "close", "quote_volume", "taker_buy_quote_volume"]].notna().all(axis=1)\n    expected_close = pd.Series(kline.index + pd.Timedelta(minutes=5) - pd.Timedelta(milliseconds=1), index=kline.index)\n    kline["close_ts"] = pd.to_datetime(kline["close_ts"], utc=True).where(kline["close_ts"].notna(), expected_close)\n    invalid_ohlc = kline["bar_present"] & (\n        (kline["high"] < kline[["open", "close", "low"]].max(axis=1))\n        | (kline["low"] > kline[["open", "close", "high"]].min(axis=1))\n        | (kline["quote_volume"] < 0)\n        | (kline["taker_buy_quote_volume"] < 0)\n        | (kline["taker_buy_quote_volume"] > kline["quote_volume"] * 1.000001)\n    )\n    if bool(invalid_ohlc.any()):\n        raise RuntimeError(f"invalid OHLCV rows: {int(invalid_ohlc.sum())}")\n\n    metrics = pd.read_parquet(source["metrics"]["local_path"])\n'''))
repls.append(('''def build_features(kline: pd.DataFrame) -> pd.DataFrame:\n    df = kline.copy()\n    log_close = np.log(df["close"].where(df["close"] > 0))\n''','''def build_features(kline: pd.DataFrame) -> pd.DataFrame:\n    df = kline.copy()\n    present = df.get("bar_present", df[["open", "high", "low", "close"]].notna().all(axis=1)).astype(bool)\n    log_close = np.log(df["close"].where(df["close"] > 0))\n'''))
repls.append(('''    df["atr48"] = tr.shift(1).rolling(48, min_periods=24).mean()\n    entry = df["open"].shift(-1)\n    for h in HORIZONS:\n        df[f"fwd{h}"] = np.log(df["open"].shift(-(1 + h)) / entry)\n    return df\n''','''    contiguous_history = present.shift(1).rolling(48, min_periods=48).sum().eq(48)\n    df["atr48"] = tr.shift(1).rolling(48, min_periods=48).mean().where(contiguous_history)\n    entry = df["open"].shift(-1)\n    for h in HORIZONS:\n        future_present = present.shift(-1)\n        contiguous_future = future_present.iloc[::-1].rolling(h + 1, min_periods=h + 1).sum().iloc[::-1].eq(h + 1)\n        df[f"fwd{h}"] = np.log(df["open"].shift(-(1 + h)) / entry).where(contiguous_future)\n    return df\n'''))
repls.append(('''def funding_between(funding: pd.DataFrame, start: pd.Timestamp, end: pd.Timestamp) -> float:\n    if funding.empty:\n        return 0.0\n    t = funding["time"].to_numpy(dtype="datetime64[ns]")\n    a = np.searchsorted(t, np.datetime64(start.tz_convert(None)), side="right")\n    b = np.searchsorted(t, np.datetime64(end.tz_convert(None)), side="right")\n    return float(funding["rate"].iloc[a:b].sum())\n\n\ndef realistic_backtest''','''def funding_rows_between(funding: pd.DataFrame, start: pd.Timestamp, end: pd.Timestamp) -> pd.DataFrame:\n    if funding.empty:\n        return funding.iloc[0:0]\n    start = pd.Timestamp(start).tz_convert("UTC")\n    end = pd.Timestamp(end).tz_convert("UTC")\n    return funding.loc[(funding["time"] > start) & (funding["time"] <= end), ["time", "rate"]]\n\n\ndef funding_cash_pnl(\n    funding: pd.DataFrame,\n    frame: pd.DataFrame,\n    start: pd.Timestamp,\n    end: pd.Timestamp,\n    side: int,\n    qty: float,\n) -> float:\n    rows = funding_rows_between(funding, start, end)\n    if rows.empty or qty <= 0:\n        return 0.0\n    # Use only the latest completed 5-minute close available at settlement.\n    marks = frame["close"].dropna().sort_index()\n    if marks.empty:\n        return 0.0\n    settlement_times = pd.DatetimeIndex(rows["time"])\n    locs = marks.index.searchsorted(settlement_times, side="right") - 1\n    valid = locs >= 0\n    if not bool(valid.any()):\n        return 0.0\n    mark_values = marks.to_numpy(float)[locs[valid]]\n    rates = rows["rate"].to_numpy(float)[valid]\n    return float((-int(side) * float(qty) * mark_values * rates).sum())\n\n\ndef realistic_backtest'''))
repls.append(('''        if planned_exit_i >= len(frame):\n            continue\n        entry = float(frame.open.iloc[entry_i])\n''','''        if planned_exit_i >= len(frame):\n            continue\n        path = frame.iloc[entry_i : planned_exit_i + 1]\n        if len(path) != horizon + 1 or not bool(path["bar_present"].fillna(False).all()):\n            continue\n        entry = float(frame.open.iloc[entry_i])\n'''))
repls.append(('''        funding_sum = funding_between(fundings[follower], entry_time, exit_time)\n        gross = side * qty * (exit_price - entry)\n        entry_cost = qty * entry * per_side\n        exit_cost = qty * exit_price * per_side\n        funding_pnl = -side * qty * entry * funding_sum\n''','''        gross = side * qty * (exit_price - entry)\n        entry_cost = qty * entry * per_side\n        exit_cost = qty * exit_price * per_side\n        funding_pnl = funding_cash_pnl(fundings[follower], frame, entry_time, exit_time, side, qty)\n'''))
repls.append(('''                    accrued = funding_between(fundings[str(t.symbol)], pd.Timestamp(t.entry_time), day_end)\n                    value += int(t.side) * float(t.qty) * (mark - float(t.entry))\n                    value -= float(t.entry_cost) + float(t.qty) * mark * (cost_per_side_bps / 1e4)\n                    value += -int(t.side) * float(t.qty) * float(t.entry) * accrued\n''','''                    value += int(t.side) * float(t.qty) * (mark - float(t.entry))\n                    value -= float(t.entry_cost) + float(t.qty) * mark * (cost_per_side_bps / 1e4)\n                    value += funding_cash_pnl(\n                        fundings[str(t.symbol)], f, pd.Timestamp(t.entry_time), day_end, int(t.side), float(t.qty)\n                    )\n'''))
repls.append(('''    daily_ret = daily.pct_change().fillna(0.0)\n    positive = trade_df.loc[trade_df.net_pnl > 0, "net_pnl"].to_numpy() if not trade_df.empty else np.array([])\n''','''    positive = trade_df.loc[trade_df.net_pnl > 0, "net_pnl"].to_numpy() if not trade_df.empty else np.array([])\n'''))
repls.append(('''        "total_return": float(daily.iloc[-1] / initial_equity - 1.0),\n        "gmean_daily": float(np.exp(np.log1p(daily_ret).mean()) - 1.0),\n''','''        "total_return": float(daily.iloc[-1] / initial_equity - 1.0),\n        "gmean_daily": float(\n            np.exp(np.log(float(daily.iloc[-1]) / initial_equity) / max(len(daily), 1)) - 1.0\n        ) if float(daily.iloc[-1]) > 0 else -1.0,\n'''))
for old, new in repls:
    if old not in s:
        raise SystemExit("missing replacement:\n" + old[:200])
    s = s.replace(old, new, 1)
target.write_text(s, encoding="utf-8")
